# Generated by Django 2.2.4 on 2019-10-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=100)),
                ('query', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
