# Generated by Django 2.2.4 on 2019-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=20)),
                ('product_brand', models.CharField(max_length=20)),
                ('product_sub_brand', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_desc', models.CharField(max_length=5000)),
                ('proudct_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
