# Generated by Django 2.2.4 on 2019-10-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191022_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proudct_image',
            field=models.ImageField(default=None, upload_to='shop/images'),
        ),
    ]
