# Generated by Django 2.2.4 on 2019-10-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191022_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
