# Generated by Django 2.2.4 on 2019-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_type', models.CharField(default='', max_length=30)),
                ('product_brand', models.CharField(default='', max_length=30)),
                ('product_sub_brand', models.CharField(default='', max_length=30)),
                ('product_size', models.CharField(default='', max_length=30)),
                ('product_color', models.CharField(default='', max_length=20)),
                ('product_desc', models.TextField()),
                ('proudct_image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
