# Generated by Django 2.2.4 on 2019-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191022_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemJson', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('order_name', models.CharField(max_length=50)),
                ('order_address', models.CharField(max_length=500)),
                ('order_email', models.CharField(default='', max_length=50)),
                ('order_phone', models.CharField(default='', max_length=13)),
                ('order_zip', models.CharField(default='', max_length=6)),
                ('order_city', models.CharField(default='', max_length=50)),
                ('order_state', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_order_id', models.IntegerField(default=0)),
                ('update_desc', models.CharField(max_length=5000)),
                ('update_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
